In [1]:
import pandas as pd
base=pd.read_csv('house-prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650     1.0           0     0     ...          7        1180   
1      7242     2.0           0     0     ...          7        2170   
2     10000     1.0           0     0     ...          6         770   
3      5000     1.0           0     0     ...          7        1050   
4      8080     1.0           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [2]:
base.shape

(21613, 21)

In [4]:
x= base.iloc[:,5:6].values
y= base.iloc[:,2:3].values

In [5]:
x

array([[1180],
       [2570],
       [ 770],
       ...,
       [1020],
       [1600],
       [1020]], dtype=int64)

In [6]:
y

array([[221900.],
       [538000.],
       [180000.],
       ...,
       [402101.],
       [400000.],
       [325000.]])

In [8]:
#necessario escalonar porque as escalas orginais sao diferentes
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
x= scaler_x.fit_transform(x)
scaler_y = StandardScaler()
y= scaler_y.fit_transform(y)

In [9]:
x

array([[-0.97983502],
       [ 0.53363434],
       [-1.42625404],
       ...,
       [-1.15404732],
       [-0.52252773],
       [-1.15404732]])

In [10]:
y

array([[-0.86671733],
       [-0.00568792],
       [-0.98084935],
       ...,
       [-0.37586519],
       [-0.38158814],
       [-0.58588173]])

In [12]:
import tensorflow as tf

In [15]:
colunas=[tf.feature_column.numeric_column('x',shape=[1])]

In [16]:
colunas

[_NumericColumn(key='x', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [18]:
regressor=tf.estimator.LinearRegressor(feature_columns=colunas)
#warning normal de acontecer

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\phods\\AppData\\Local\\Temp\\tmpccvuelho', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001EBC83CA400>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [21]:
from sklearn.model_selection import train_test_split
x_treinamento,x_teste, y_treinamento,y_teste=train_test_split(x,y,test_size=0.3)
#test_size=0.3 30% serparado para o teste

In [23]:
x_treinamento.shape

(15129, 1)

In [24]:
y_treinamento.shape

(15129, 1)

In [25]:
x_teste.shape

(6484, 1)

In [26]:
y_teste.shape

(6484, 1)

In [27]:
funcao_treinamento=tf.estimator.inputs.numpy_input_fn({'x':x_treinamento},
                                                      y_treinamento,
                                                      batch_size=32,
                                                      num_epochs=None, #boa pratica
                                                      shuffle=True)
#foi importado o dataset com o pandas, mas depois foi convertido para numpy por isso o numpy_input

In [29]:
funcao_teste=tf.estimator.inputs.numpy_input_fn({'x':x_teste},
                                                y_teste,
                                                batch_size=32,
                                                num_epochs=1000,
                                                shuffle=False)
#foi importado o dataset com o pandas, mas depois foi convertido para numpy por isso o numpy_input

In [31]:
regressor.train(input_fn=funcao_treinamento,steps=10000)

INFO:tensorflow:Calling model_fn.


ValueError: You must provide a labels Tensor. Given: None. Suggested troubleshooting steps: Check that your data contain your label feature. Check that your input_fn properly parses and returns labels.